---
name: DockerCI

on:
  push: 
    tags: '*'
    
jobs:
  DockerCI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/hash_url:${{steps.vars.outputs.tag}}
      - name: Push the tagged Docker image
        run: docker push DOCKERHUB_${{ secrets.DOCKERHUB_USERNAME }}/hash_url:${{steps.vars.outputs.tag}}
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/hash_url:latest
      - name: Push the latest Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/angular-cli:latest
